### ISSUE TITLE
Questions about hf model

### ISSUE THREAD

**Issue by Daming-W** [moranyanuka/icc_code#1]
Hi team,
Thanks to your grear work!
I've try to run a quick demo of icc. However it seems like the huggingface files are incompleted.
Could you double check that or let me know if I missed some key steps.

Many thx!
![image](https://github.com/user-attachments/assets/a4c1aeed-200d-4d23-bde6-a5530816234f)

**Comment by moranyanuka** [comment]
Thank you for trying our model! 

Could you please share with the code you have used to load the model?
Also, can you try running:
`pip install -U transformers`
And then try loading it again?

**Comment by Daming-W** [comment]
It seems that the transformers problem has been solved by upgrading.
Thanks for your tip!
